#!/bin/bash

set -euo pipefail

# https://www.terraform.io/docs/internals/credentials-helpers.html
# Environment variable format: TF_TOKEN_<hostname>.
# Hostname should have `.` characters replaced with `_`, as it is difficult
# to set environment variables with dots in name.
# Example: TF_TOKEN_app_terraform_io=abc123

usage() {
  cat << EOF >&2
Usage: terraform-credentials-env get <hostname>
Terraform credentials helper that reads token from environment variables.
Only "get" is supported, "store" and "forget" are ignored.
EOF
}

if [[ $# -ne 2 ]]; then
  usage
  exit 1
fi

readonly tf_verb=$1
readonly tf_hostname=$2

case $tf_verb in
"get")
  readonly env_name="TF_TOKEN_${tf_hostname//./_}"
  readonly token="${!env_name:-}"
  if [[ -n $token ]]; then
    printf '{ "token": "%s" }\n' "$token"
  else
    echo '{}'
  fi
  ;;
"store")
  cat > /dev/null
  usage
  exit 1
  ;;
"forget")
  usage
  exit 1
  ;;
esac
